name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Release
        arch:
          - x64
        include:
          - arch: x64
            platform: x64
    steps:
      - name: Check out files
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install Premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Generate project files
        run: premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} ${{matrix.arch}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} build/iw4-validator.sln

      - name: Upload ${{matrix.configuration}} ${{matrix.arch}} binaries
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Windows ${{matrix.configuration}} ${{matrix.arch}} binaries
          path: |
            build/bin/${{matrix.arch}}/${{matrix.configuration}}/iw4-validator.exe
            build/bin/${{matrix.arch}}/${{matrix.configuration}}/iw4-validator.pdb

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Release
        arch:
          - x64
          - arm64
        include:
          - configuration: Release
            config: release
    steps:
      - name: Check out files
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Install dependencies (arm64)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install crossbuild-essential-arm64 -y

      - name: Install Premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Generate project files
        run: premake5 gmake2

      - name: Set up problem matching
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Set up CC environment variable
        if: matrix.arch == 'arm64'
        run: |
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Set up CXX environment variable
        if: matrix.arch == 'arm64'
        run: |
          echo "CXX=aarch64-linux-gnu-g++" >> $GITHUB_ENV

      - name: Build ${{matrix.configuration}} ${{matrix.arch}} binaries
        run: |
          pushd build
          make config=${{matrix.config}}_${{matrix.arch}} -j$(nproc)

      - name: Upload ${{matrix.configuration}} ${{matrix.arch}} binaries
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Linux ${{matrix.configuration}} ${{matrix.arch}} binaries
          path: |
            build/bin/${{matrix.arch}}/${{matrix.configuration}}/iw4-validator

  deploy:
    name: Deploy artifacts
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master')
    steps:
      - name: Setup main environment
        if: github.ref == 'refs/heads/master'
        run: echo "ALTERWARE_MASTER_PATH=${{ secrets.ALTERWARE_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      - name: Download Release binaries
        uses: actions/download-artifact@v3.0.2
        with:
          name: Windows Release x64 binaries

      # Set up committer info and GPG key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.ALTERWARE_MASTER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.ALTERWARE_MASTER_SSH_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Upload iw4-validator binary
        run: rsync -avz iw4-validator.exe ${{ secrets.ALTERWARE_MASTER_SSH_USER }}@${{ secrets.ALTERWARE_MASTER_SSH_ADDRESS }}:${{ env.ALTERWARE_MASTER_PATH }}/tools/
